### ISSUE TITLE
Unable to build InteropTests

### ISSUE THREAD

**Issue by Noemata** [tristanlabelle/swift-winrt#396]
After using the following build steps (literally)

cd swift-winrt
cmake --preset debug -D CMAKE_EXPORT_COMPILE_COMMANDS=OFF
cmake --build --preset debug

swift build --verbose --build-tests
swift test --verbose --skip-build

cd generator
swift build --verbose --build-tests
swift test --verbose --skip-build

cmake --preset debug
cmake --build --preset debug

```
Open separate x64 command prompt or from here 
Launch devenv from there
Select Generator folder
Switch to CMake Targets View
Select NuGetPackage
Build NuGetPackage
Exit VS
Then ...
```
(Created SWIFTWINRT_EXE target variable from above ref)
cd ..\Interoptests
swift build --verbose --build-tests
swift test --verbose --skip-build

----------------------------------

The build fails at the commented out dd_subdirectory below:

```
# Support using this directory as a standalone project or as a subdirectory.
if("${CMAKE_CURRENT_SOURCE_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
    cmake_minimum_required(VERSION 3.21.0)

    project(InteropTests LANGUAGES C Swift)
endif()

if (NOT DEFINED SWIFTWINRT_EXE)
    message(FATAL_ERROR "SWIFTWINRT_EXE must be defined")
endif()
cmake_path(ABSOLUTE_PATH SWIFTWINRT_EXE NORMALIZE)

# Build the support module if not already the case (by root CMakeLists.txt)
if(NOT TARGET WindowsRuntime)
    execute_process(
        COMMAND git.exe -C "${CMAKE_CURRENT_SOURCE_DIR}" rev-parse --path-format=absolute --show-toplevel
        OUTPUT_VARIABLE REPO_ROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
    #add_subdirectory("${REPO_ROOT}/Sources" "${CMAKE_CURRENT_BINARY_DIR}/Support")
endif()

add_subdirectory(WinRTComponent)
```

**Comment by Noemata** [comment]
I was only able to build the nuget package with the approach shown above.  Clearly, I'm not understanding something about that part of the build.  The InteropTests build failure another bit I'm not understanding.

**Comment by Noemata** [comment]
Looks like the commented line should have been:

add_subdirectory("${REPO_ROOT}/Support/Sources" "${CMAKE_CURRENT_BINARY_DIR}/Support")

**Comment by tristanlabelle** [comment]
InteropTests can only be (fully) built with SPM because of the XCTest dependency (maybe at some point I'll switch to `swift-testing`). So the build instructions to follow are that of the `spm-generator-and-interoptests` workflow job. You don't need to generate the nuget package, it will use the exe build in the repo directly.

The commands you used included building with CMake in the `InteropTests` subfolder. Looks like I tried to make that possible as a way to iterate on WinRTComponent with a scoped-down environment, but since we need SPM for building the tests anyways (can't build XCTests with CMake), I haven't been relying on this code path and you found a bug that slipped in. I'll fix it, thanks!

**Comment by Noemata** [comment]
I see.  I do like having the option of building some of these bits with CMake.  If for no other reason than to have examples of doing so in case I need to do like dev work.  SPM, as you've already noted, has limitations.

**Comment by tristanlabelle** [comment]
Actually I can require the Swift 6+ for the tests in this repo without requiring it to build the code generator or generated code.
